Repository yardenshoham/seret, pull requests merged in 2023-08, with the labels that each got.

#1 added Dockerfile
  .dockerignore
  Dockerfile
Labels: size/S

#3 Issue #2 Added tests
  .github/workflows/deno-test.yml
  README.md
  deno.json
  routes/movie/$movie.tsx
  services/cinema_city.ts
  services/movieland.ts
Labels: size/M

#5 Issue 4
  Dockerfile
Labels: size/XS

#7 Reorder movie page
  .vscode/settings.json
  routes/movie/$movie.tsx
Labels: size/M

#8 Readable date
  routes/movie/$movie.tsx
Labels: size/S

#9 Add grid to movie page
  routes/movie/$movie.tsx
Labels: size/M

#10 Don't show past showings
  routes/movie/$movie.tsx
Labels: size/S

#11 Use dark theme
  routes/_app.tsx
Labels: size/S

#12 Remove spacing
  routes/index.tsx
Labels: size/XS

#13 Make the design responsive
  routes/_app.tsx
  routes/index.tsx
  routes/movie/$movie.tsx
Labels: size/M

#14 Add images
  routes/index.tsx
  routes/movie/$movie.tsx
  services/cinema_city.ts
  services/movieland.ts
  services/movies.ts
  types.ts
Labels: size/L

#15 Add gitpod
  .gitpod.Dockerfile
  .gitpod.yml
Labels: size/S

#18 Prepend 0 in hour
  routes/_export.ts
  routes/movie/$movie.tsx
Labels: size/S

#19 Add hot cinema
  services/hot_cinema.ts
  services/movies.ts
  types.ts
Labels: size/M

#20 Faster loading logic
  routes/_export.ts
  services/movies.ts
Labels: size/S

#21 Refactor movies service and types
  services/movies.ts
  types.ts
Labels: size/XS

#22 Deno devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  routes/_export.ts
Labels: size/M

#24 Let GitHub know which files are generated
  .gitattributes
Labels: size/XS
